# Generated by Django 3.2.7 on 2021-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchase_data', models.DateTimeField(verbose_name='when buy?')),
                ('cur_price', models.IntegerField(default=0)),
                ('roi', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
