# Generated by Django 3.2.7 on 2021-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kstock',
            old_name='cur_price',
            new_name='buy_price',
        ),
        migrations.RemoveField(
            model_name='kstock',
            name='roi',
        ),
        migrations.AlterField(
            model_name='kstock',
            name='purchase_data',
            field=models.DateField(verbose_name='when buy?'),
        ),
    ]
