# Generated by Django 3.2.7 on 2021-10-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211012_0122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
